### ISSUE TITLE
Why all one file for weapon defs

### ISSUE THREAD

**Issue by Beanzilla** [natelastname/ctf_guns#1]
I would have separated them out into `weapon_defs_t1.lua` or even `weapon_defs_tier1.lua`.

> This is a minor detail for concern though, so I'm just pointing out a detail I would have done differently.

This idea of multiple files would allow a user to choose what tier weapons are available, and also allows better organizing of the weapons for when/if more new weapons come along. (It also makes it a little better on debugging)

> But meh again, this isn't a top concern as this is more of an opinion. (Still great mod)

**Comment by natelastname** [comment]
There is no reason, it's just a choice that I made while coding. 

If you wanted to add a settings.conf file defining settings to enable/disable the various tiers as well as the neccessary checks to implement those settings, that would absolutely be welcome.  This may or may not involve breaking up wep_defns.lua into multiple files.

**Comment by Beanzilla** [comment]
Yup, and as I state it's really just an optional preference. (not a big deal)

I might throw in a settings file. (I could keep it the current way or break it up... really it's up to you)

> I'm leaning on keeping all in one file... for now, just so it doesn't change workflow too much.

**Comment by Beanzilla** [comment]
Closing... It's in a PR
